{{- if .Values.rbac.create }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kaniop.fullname" . }}
  labels:
    {{- include "kaniop.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - kaniop.rs
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - pods/exec
      - secrets
      - services
    verbs:
      - '*'
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - '*'
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - list
      - get
      - create
      - update
      - watch
{{- end }}
