{{- if .Values.metrics.prometheusRules.enabled -}}
---
kind: PrometheusRule
apiVersion: monitoring.coreos.com/v1
metadata:
  name: prometheus-ceph-rules
  namespace: {{ .Values.metrics.prometheusRules.namespaceOverride | default .Release.Namespace }}
  labels:
    {{- include "kaniop.labels" . | nindent 4 }}
    {{- with .Values.metrics.prometheusRules.additionalLabels }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  {{- with .Values.metrics.prometheusRules.annotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
spec:
  {{- $defaultRules := .Files.Get "files/prometheusrules.yaml" | fromYaml }}
  groups:
  {{- range $group := $defaultRules.groups }}
    {{- $rules := list }}
    {{- range $rule := $group.rules }}
      {{- $ruleName := ternary $rule.alert $rule.record (hasKey $rule "alert") }}
      {{- $ruleOverrides := get $.Values.metrics.prometheusRules.overrides $ruleName }}
      {{- if $ruleOverrides }}
        {{- if not $ruleOverrides.disabled }}
          {{- $ruleMerged := mergeOverwrite $rule $ruleOverrides }}
          {{- $rules = append $rules $ruleMerged }}
        {{- end }}
      {{- else }}
        {{- $rules = append $rules $rule }}
      {{- end }}
    {{- end }}
    {{- if gt (len $rules) 0 }}
    - name: {{ $group.name }}
      rules:
        {{- $rules | toYaml | nindent 8 }}
    {{- end }}
  {{- end }}
{{- end }}
