apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: kanidm-service-account-validation-policy
spec:
  matchConstraints:
    resourceRules:
      - apiGroups:
          - kaniop.rs
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - kanidmserviceaccounts
  validations:
    # Validations for apiTokens.secretName cannot be defined in the CRD schema because cost exceeds
    # budget limit.
    - expression: |
        !has(object.spec.apiTokens) || object.spec.apiTokens.all(
          t,
          !has(t.secretName) || t.secretName.matches(r'^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$')
        )
      message: "secretName must be a valid Kubernetes resource name."
    - expression: |
        !has(object.spec.apiTokens) || object.spec.apiTokens.all(
          t,
          !has(t.secretName) || object.spec.apiTokens.filter(t2, has(t2.secretName) && t2.secretName.lowerAscii() == t.secretName.lowerAscii()).size() == 1
        )
      message: "secretName must be unique across all API tokens (case-insensitive)."
    - expression: |
        !has(object.spec.apiTokens) || object.spec.apiTokens.all(
          t,
          object.spec.apiTokens.filter(t2, t2.label.lowerAscii() == t.label.lowerAscii()).size() == 1
        )
      message: "label must be unique across all API tokens (case-insensitive)."
