{{- if .Values.crdMigration.personAccountPlural.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kaniop.crdMigration.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-30"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "kaniop.crdMigration.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
