[book]
authors = ["Pando85 <pando855@gmail.com>"]
language = "en"
multilingual = false
src = "src"
title = "Kaniop book"

[build]
build-dir = "pando85.github.io/docs/kaniop/master"

[output.markdown]
