name: Rust

on:
  push:
    branches: [master]
    tags:
      - v*
  pull_request:
    branches: [master]

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install fmt with stable toolchain
        id: toolchain
        uses: dtolnay/rust-toolchain@stable

      - run: rustup override set ${{steps.toolchain.outputs.name}}
      - run: rustup component add rustfmt

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install clippy with stable toolchain
        id: toolchain
        uses: dtolnay/rust-toolchain@stable
      - run: rustup override set ${{steps.toolchain.outputs.name}}
      - uses: Swatinem/rust-cache@v2
      - run: rustup component add clippy

      - uses: clechasseur/rs-clippy-check@v3
        with:
          args: --locked --all-targets --all-features

  build:
    strategy:
      fail-fast: false
      matrix:
        job:
          - {os: ubuntu-24.04, target: aarch64-unknown-linux-gnu, use-cross: true}
          - {os: ubuntu-24.04, target: x86_64-unknown-linux-gnu}
    name: (${{ matrix.job.os }}) ${{ matrix.job.target }}
    runs-on: ${{ matrix.job.os }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install prerequisites
        shell: bash
        run: |
          case ${{ matrix.job.target }} in
            arm-unknown-linux-*) sudo apt-get -y update ; sudo apt-get -y install gcc-arm-linux-gnueabihf ;;
            aarch64-unknown-linux-gnu) sudo apt-get -y update ; sudo apt-get -y install gcc-aarch64-linux-gnu ;;
          esac

      - name: Install Rust toolchain
        id: toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.job.target }}

      - run: rustup override set ${{steps.toolchain.outputs.name}}

      - uses: Swatinem/rust-cache@v2
        with:
          # not reuse cache between different targets:
          # https://github.com/cross-rs/cross/issues/39#issuecomment-270684223
          key: ${{ matrix.job.target }}
          workspaces: ". -> target-${{ matrix.job.target }}"

      - name: Run tests
        run: CARGO_TARGET=${{ matrix.job.target }} make test

      - name: Run integration tests
        run: CARGO_TARGET=${{ matrix.job.target }} make integration-test

      # Run e2e tests only on x86_64 target until we have aarch64 runner
      - name: Install kind
        if: matrix.job.use-cross != true
        uses: helm/kind-action@v1.12.0
        with:
          install_only: true

      - name: Install helm
        if: matrix.job.use-cross != true
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh

      - name: Run e2e tests
        if: matrix.job.use-cross != true
        run: CARGO_TARGET=${{ matrix.job.target }} E2E_LOGGING_LEVEL=info make e2e-test

      - name: Publish crates
        if: matrix.job.use-cross != true && startsWith(github.ref, 'refs/tags/')
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        shell: bash
        run: |
          cargo login "${CRATES_IO_TOKEN}"
          make publish
